server:
  port: 8089
  servlet:
    context-path: '/Culinaryapi-Order-Service/'

spring:
  application:
    name: CulinaryApi-OrderService
  datasource:
    url: jdbc:postgresql://localhost:5432/Culinaryapi-OrderService
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://gxfhiqck:3sivG1zlLvv3W7SWQcK14y010juFScxm@leopard.lmq.cloudamqp.com/gxfhiqck

Culinary:
  broker:
    exchange:
      userEventExchange: Culinary.userEvent
      userServiceEventExchange: Culinary.userServiceEvent
      menuEventExchange: Culinary.MenuService
      orderServiceEventExchange: Culinary.OrderService
    queue:
      userEventQueue:
        name: Culinary.UserEvent.OrderService
      userServiceEventQueue:
        name: Culinary.UserServiceEvent.OrderService
      menuServiceEventQueue:
        name: Culinary.MenuEvent.OrderService
  auth:
    jwt-secret: ZHsOVU5Y6gGU3/S9WZfY5W/Ni6ZixK0I9rZ44MudSRuNYvib+ZoeP/YQNfEvXlDhEgV60Ma8csbcv6ALfOjdyMg==